package com.mst.db.dao;

import com.mst.db.domain.UserDetailInfo;
import com.mst.db.domain.UserDetailInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserDetailInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail_info
     *
     * @mbg.generated
     */
    long countByExample(UserDetailInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail_info
     *
     * @mbg.generated
     */
    int deleteByExample(UserDetailInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail_info
     *
     * @mbg.generated
     */
    int insert(UserDetailInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail_info
     *
     * @mbg.generated
     */
    int insertSelective(UserDetailInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UserDetailInfo selectOneByExample(UserDetailInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UserDetailInfo selectOneByExampleSelective(@Param("example") UserDetailInfoExample example, @Param("selective") UserDetailInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<UserDetailInfo> selectByExampleSelective(@Param("example") UserDetailInfoExample example, @Param("selective") UserDetailInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail_info
     *
     * @mbg.generated
     */
    List<UserDetailInfo> selectByExample(UserDetailInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UserDetailInfo selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") UserDetailInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail_info
     *
     * @mbg.generated
     */
    UserDetailInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserDetailInfo record, @Param("example") UserDetailInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserDetailInfo record, @Param("example") UserDetailInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserDetailInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserDetailInfo record);
}