spring:
  profiles:
    active: db
  message:
    encoding: UTF-8

server:
  port: 8888

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    org.mst.core:  ERROR
    org.mst.db:  ERROR
    org.mst.front:  ERROR